<template>
  <div class="inGame">
    <div
      v-for="index in 3"
      :key="index"
      class="inGame__animation"
    >
      <player></player>
    </div>
    <div class="inGame__statusWrapper">
      <v-btn rounded color="black" dark>
        QUIT
      </v-btn>
      <v-navigation-drawer
        v-model="drawer"
        absolute
        right
        temporary
        class="chat"
      >
        <div
          class="chat__message-wrapper"
          v-for="(message, index) in messages"
          :key="index"
        >
          <span class="chat__user">{{ message.user }}: </span>
          <span class="chat__message">{{ message.text }}</span>
        </div>

        <template v-slot:append>
          <v-text-field
            :type="'text'"
            value=""
            outlined
            solo
            class="chat__input"
            v-model="message"
          >
          </v-text-field>
          <v-btn @click.native="sendMessage" class="chat__submit">send</v-btn>
        </template>
      </v-navigation-drawer>
      <div class="inGame__roundWrapper">
        <span class="inGame__round">
          ROUND
        </span>
        <span class="inGame__round">
          {{ currentRound }} / {{ totalRounds }}
        </span>
      </div>
      <player></player>
    </div>
    <div class="inGame__mainCardWrapper">
      <card
        isCzar
        text="Exercitation sint Lorem deserunt excepteur aliquip laboris in
            ullamco veniam dolore nostrud."
      ></card>
      <div class="inGame__chatButtonWrapper">
        <v-btn
          rounded
          color="black"
          dark
          @click.native="chatNotification = false"
          @click.stop="drawer = !drawer"
        >
          CHAT
        </v-btn>
        <div v-if="chatNotification" class="inGame__chatNotification blink">
          !
        </div>
      </div>
    </div>
    <div class="inGame__cardCarouselWrapper">
      <span class="inGame__hint">
        Choose {{cardsToPick}} of the following cards!
      </span>
      <cardCarousel :cardsToPick="cardsToPick"></cardCarousel>
    </div>
    <div class="inGame__userCarouselWrapper">
      <userCarousel></userCarousel>
    </div>
  </div>
</template>
<script>
import cardCarousel from "./components/cardCarousel";
import card from "./components/card";
import player from "./components/player";
import userCarousel from "./components/userCarousel";
import anime from "animejs/lib/anime.es.js";

export default {
  components: {
    cardCarousel,
    card,
    player,
    userCarousel
  },
  methods: {
    sendMessage() {
      if (this.message) {
        this.messages.push({
          user: this.username,
          text: this.message
        });
        //reset input
        this.message = "";
        //wait 0.01 secs because we need to add element
        setTimeout(this.scrollToLastMessage, 10);
      }
    },
    scrollToLastMessage() {
      //element generated by vuetify
      var test = document.getElementsByClassName(
        "v-navigation-drawer__content"
      )[0];

      //scroll to the end of the container
      test.scrollTop = test.scrollHeight;
    },
    nextRoundAnimation(i) {
      var translate_y;
      i++;
      switch (i) {
        case 1:
          translate_y = 100;
          break;
        case 2:
          translate_y = 400;
          break;
          case 3:
          translate_y = 250;
          break;
      }
      anime({
        targets: `.inGame__animation:nth-child(${i})`,
        translateY: [500, translate_y],
        duration: 2000,
        easing: "easeInOutQuart",
        opacity: [0, 1],
        complete: () =>
          anime({
            targets: `.inGame__animation:nth-child(${i})`,
            scale: [1, 2],
            direction: "alternate",
            easing: "easeInOutSine",
            duration: 1000,
            complete: () =>
              anime({
                targets: `.inGame__animation:nth-child(${i})`,
                scale: 2,
                translateY: 0+translate_y/2.5,
                easing: "easeInOutQuart",
                duration: 1000,
                opacity: [1, 0]
              })
          })
      });
      if (i <= 3) {
        this.nextRoundAnimation(i);
      }
    }
  },
  data() {
    return {
      animationTimeline: anime.timeline(),
      username: "Kotsovolos",
      message: "",
      chatNotification: true,
      currentRound: 1,
      totalRounds: 6,
      drawer: false,
      cardsToPick:1,
      messages: [
        {
          user: "stougk",
          text: "foveri ergasia , 10/10"
        },
        {
          user: "dtektoni",
          text: "amazing, WOW , 10/10"
        },
        {
          user: "asidirop",
          text: "oti kalutero exoume dei, evge , 10/10"
        },
        {
          user: "stougk",
          text: "foveri ergasia , 10/10"
        },
        {
          user: "dtektoni",
          text: "amazing, WOW , 10/10"
        },
        {
          user: "asidirop",
          text: "oti kalutero exoume dei, evge , 10/10"
        },
        {
          user: "stougk",
          text: "foveri ergasia , 10/10"
        },
        {
          user: "dtektoni",
          text: "amazing, WOW , 10/10"
        },
        {
          user: "asidirop",
          text: "oti kalutero exoume dei, evge , 10/10"
        },
        {
          user: "stougk",
          text: "foveri ergasia , 10/10"
        },
        {
          user: "dtektoni",
          text: "amazing, WOW , 10/10"
        },
        {
          user: "asidirop",
          text: "oti kalutero exoume dei, evge , 10/10"
        },
        {
          user: "stougk",
          text: "foveri ergasia , 10/10"
        },
        {
          user: "dtektoni",
          text: "amazing, WOW , 10/10"
        },
        {
          user: "asidirop",
          text: "oti kalutero exoume dei, evge , 10/10"
        }
      ]
    };
  },
  mounted() {
    this.nextRoundAnimation(0);
  }
};
</script>
